# Generated by Django 3.0.2 on 2020-08-29 09:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('shop', '0011_auto_20200828_1607'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImportantOccasionModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('occasion_name', models.CharField(max_length=256)),
                ('occasion_body', models.TextField()),
                ('occasion_date', models.DateTimeField(auto_now_add=True)),
                ('completed', models.BooleanField(blank=True, default=False, null=True)),
                ('product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='shop.ProductModel')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
