# Generated by Django 3.0.2 on 2020-08-30 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pandorApi', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='importantoccasionmodel',
            name='occasion_date',
            field=models.DateTimeField(verbose_name='Y-M-D'),
        ),
    ]
