# Generated by Django 3.0.2 on 2020-08-30 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pandorApi', '0002_auto_20200830_1635'),
    ]

    operations = [
        migrations.AlterField(
            model_name='importantoccasionmodel',
            name='occasion_date',
            field=models.DateTimeField(),
        ),
    ]
