# Generated by Django 3.0.2 on 2020-08-25 17:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productimagemodel',
            old_name='hotel',
            new_name='product',
        ),
        migrations.CreateModel(
            name='AvailabilityModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('store_name', models.CharField(max_length=255)),
                ('number_of_available_items', models.IntegerField()),
                ('online_exclusive', models.BooleanField()),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.ProductModel')),
            ],
        ),
    ]
