# Generated by Django 3.0.2 on 2020-08-25 19:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_auto_20200825_1918'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ordermodel',
            name='amount',
        ),
        migrations.AddField(
            model_name='checkmodel',
            name='amount',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ordermodel',
            name='available',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='shop.AvailabilityModel'),
        ),
        migrations.AlterField(
            model_name='checkmodel',
            name='total_price',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=10),
            preserve_default=False,
        ),
    ]
