# Generated by Django 3.0.2 on 2020-08-25 19:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_auto_20200825_2127'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ordermodel',
            name='price_of_order',
        ),
    ]
