# Generated by Django 3.0.2 on 2020-08-25 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_remove_ordermodel_price_of_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='checkmodel',
            name='check_date',
            field=models.DateField(auto_now_add=True),
            preserve_default=False,
        ),
    ]
