# Generated by Django 3.0.2 on 2020-08-26 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_checkmodel_check_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='checkmodel',
            name='amount',
        ),
        migrations.AddField(
            model_name='ordermodel',
            name='amount',
            field=models.IntegerField(default=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ordermodel',
            name='price_of_order',
            field=models.DecimalField(decimal_places=2, default=70, max_digits=10),
            preserve_default=False,
        ),
    ]
