# Generated by Django 3.0.2 on 2020-08-26 07:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0006_auto_20200826_0927'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CheckModel',
        ),
    ]
